### PR TITLE
Localization sp3

### PR DESCRIPTION
**Pull request by jreidinger**
caasp2-language

### CODE REVIEW

**Review by imobachgs — COMMENTED** [review]
It looks good. I guess you will need to finish changes in yast2-country in order to be able to update dependencies for this package.

**Comment by jreidinger** [comment]
@imobachgs yes, yast2-country changes is required and I will update dependency when it will have new version.

**Comment by jreidinger** [comment]
@imobachgs note. version is 1.1.1.1 because 1.1.2 is already used in SLE15

**Review by imobachgs — APPROVED** [review]
LGTM. Let's wait for Travis opinion :)

**Comment by jreidinger** [comment]
travis failed due to missing newer yast2-country in travis. Locally builds fine.

**Pull request merged**
