### PR TITLE
Fix system roles

### PR DESCRIPTION
**Pull request by imobachgs**
Fixes [bsc#1038854](https://bugzilla.opensuse.org/show_bug.cgi?id=1038854).

### CODE REVIEW

**Review by lslezak — APPROVED** [review]
LGTM

**Comment by imobachgs** [comment]
@DimStar77 spot another problem, so I've added the fix. @lslezak Could you have a second look?

**Review by lslezak — APPROVED** [review]
LGTM

**Comment by imobachgs** [comment]
Thanks!

**Pull request merged**
